handlers:
- url: '/'
  static_files: 'mainsite/index.html'
  upload: '.*'
- url: '/demos/fullscreen/'
  static_files: 'dev/demos/fullscreen/fullscreen.html'
  upload: '.*'
- url: '/'
  static_dir: '/'
